- src/components/ConnectFreighter.astro
- src/components/borrowing.astro
Just quick fixing to get deployment done before kick-off
> Fix some errors in FE code

- contracts/loan_manager/src/positions.rs
- contracts/loan_manager/src/storage_types.rs
- contracts/loan_pool/src/positions.rs
- contracts/loan_pool/src/storage_types.rs
Changed the way we handled positions in loan pools and loans in loan manager to use custom struct types.
> refactor: custom types for storage

- .github/workflows/deploy.yml
- astro.config.mjs
- public/CNAME
Added workflow to deploy automatically to laina-de.fi
> chore: actions to deploy pages

- src/pages/_lend/LendableAssetCard.tsx
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
Hotfix'd. Removed unused variable!
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:
> fix: removed unused variable

- initialize.js
- src/components/Loading.tsx
- src/currencies.ts
- src/lib/converters.ts
- src/pages/_borrow/BorrowModal.tsx
- src/pages/_borrow/BorrowableAssetCard.tsx
- src/pages/_lend/DepositModal.tsx
- src/pages/_lend/LendableAssetCard.tsx
- src/stellar-wallet.tsx
* Fix: non unique modal ids
* Add borrow modal
* Got the contractIds to the frontend during initialize.js
* The modal not very failsafe, as no health calculation in the frontend yet
* Refetch balances when the user deposits or borrows
> Feat: Borrow modal, refetch balances on deposit/borrow

- src/components/Nav.tsx
- src/stellar-wallet.tsx
Hätänen integraatio Stellar-Wallets-Kitin namiskaan. Toimii hienosti, ja muistaa myös walletin refreshien välissä.
Ei tyylikkäin toteutus, paukuttaa warningeja kun effectit laukeaa useaan kertaan, mutta toimii.
> feat: Use Stellar-Wallets-Kit button.

- src/components/Button.tsx
- src/components/Footer.tsx
- src/components/Nav.tsx
- src/layouts/Layout.astro
- src/pages/_borrow/BorrowPage.tsx
- src/pages/_landing/LandingPage.tsx
- src/pages/_lend/LendPage.tsx
- src/pages/_liquidate/LiquidatePage.tsx
Nyt ländäri näyttää ihan ok:lta puhelimella. Piti piilottaa toi navivalikko mobiilissa, tarvii miettiä oisko sille joku parempi ratkasu, esim tabit navipalkin alapuolella. Muut näkymät edelleen paskoja mobiililla.
> Feat: Responsive landing page

- contracts/loan_manager/src/contract.rs
- contracts/loan_pool/src/contract.rs
- contracts/loan_pool/src/pool.rs
- contracts/loan_pool/src/positions.rs
- contracts/loan_pool/src/storage_types.rs
- Positions and loan balances are now calculated correctly
- add_interest now adds the interest both to the loan balances and liabilities in pools
> Feat: calculate pool balances correctly

- contracts/loan_manager/src/contract.rs
- contracts/loan_manager/src/positions.rs
- contracts/loan_manager/src/storage_types.rs
- contracts/loan_pool/src/contract.rs
> feat: add repayment functionality

- contracts/loan_pool/src/contract.rs
- src/pages/_borrow/BorrowableAssetCard.tsx
- Added a getter to pool contract for available balance
- Added available balance to borrow page
> Feat: balance to borrow UI

- src/pages/_borrow/BorrowModal.tsx
- src/pages/_borrow/BorrowableAssetCard.tsx
- src/pages/_welcome/WelcomePage.tsx
* Fix incorrect text in welcome page deposit card
* Disable borrow on empty pools
* Set max loan to the amount of assets in the pool
> feat: Frontend tweaks

- contracts/loan_manager/src/contract.rs
- contracts/loan_pool/src/contract.rs
- Paid loans are now removed from the storage
- Locked collateral is returned as the loan is closed
> Fix: remove paid loans

- contracts/loan_manager/src/contract.rs
Changed the amount of collateral withdrawn.
> Fix: wrong amount of collateral withdrawn

- contracts/loan_manager/src/contract.rs
- contracts/loan_manager/src/interest.rs
- contracts/loan_pool/src/contract.rs
- Added variable interest rate inside contracts based on the ratio of available and total balance in pools
- Added a getter for interest rates
- It should be added that base, rate at panic and max interest rates should be added to pools as pool parameters in the future
> feat: variable interest rate for contracts

- src/pages/_borrow/BorrowModal.tsx
Accidentally hardcoded the max loan. My bad.
> fix: Incorrect max loan.

- currencies.ts
- src/components/Alert.tsx
- src/components/Card.tsx
- src/components/CryptoAmountSelector.tsx
- src/lib/horizon.ts
- src/pages/_borrow/BorrowModal.tsx
- src/pages/_borrow/BorrowModal/BorrowModal.tsx
- src/pages/_borrow/BorrowModal/BorrowStep.tsx
- src/pages/_borrow/BorrowModal/TrustlineStep.tsx
- src/pages/_borrow/BorrowableAsset.tsx
- src/pages/_lend/DepositModal.tsx
- src/pages/_lend/LendableAsset.tsx
- src/stellar-wallet.tsx
* Added a check for trustline to the borrow flow
* If a trustline doesn't exist, prompt the user to create it
* Refactored the balance datamankelointi a bit. Now it actually checks the balance & trustline for all the supported tickers.
> feat: Check trustline before letting the user borrow.

- src/pages/_landing/LandingPage.tsx
- Changed Stellar dev discord link to our own channels.
> Feat: laina discord to lander

- contracts/loan_manager/src/contract.rs
- contracts/loan_pool/src/contract.rs
- Added timestamp update to accrual update
- Added accrual update call to add_interest
> fix: add accrual to repay

- package.json
- src/components/AssetsModal/WithdrawView.tsx
- src/components/Dialog.tsx
- src/components/LoansModal/RepayView.tsx
- src/contexts/loan-context.tsx
- src/contexts/wallet-context.tsx
- src/pages/_borrow/BorrowModal/BorrowModal.tsx
- src/pages/_borrow/BorrowModal/BorrowStep.tsx
- src/pages/_borrow/BorrowModal/TrustlineStep.tsx
- src/pages/_lend/DepositModal.tsx
- tailwind.config.mjs
* refactor: Deposit transaction logic into a hook
* refactor: Dialog into its own component, includes repeated state dialogs (loading, success, error)
* refactor: Set publickey for our contractClients during wallet connection
* feat: Improved loading, success & error states for depositmodal & borrowmodal
> feat: Deposit & Borrow success notifications

- src/components/Link.tsx
- src/pages/_borrow/BorrowModal/BorrowModal.tsx
- src/pages/_borrow/BorrowPage.tsx
- src/pages/_borrow/BorrowableAsset.tsx
- src/pages/_lend/DepositModal.tsx
- src/pages/_lend/LendPage.tsx
- src/pages/_lend/LendableAsset.tsx
Fixed by lifting the modals up in the DOM, out of the table. This also removes bloat from our DOM.
> Fix: <dialog> cannot be a child of <tr>

- src/pages/_borrow/BorrowableAsset.tsx
- src/pages/_lend/DepositModal.tsx
- src/pages/_lend/LendableAsset.tsx
* fix: padding differences between lend & borrow assets
* fix: deposit modal jerking if you're rich
> Fix: frontend UI glitches

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/components/AssetsModal/AssetsModal.tsx
- src/components/AssetsModal/PositionsView.tsx
- src/components/AssetsModal/WithdrawView.tsx
- src/components/CryptoAmountSelector.tsx
- src/components/LoansModal/LoansModal.tsx
- src/components/LoansModal/RepayView.tsx
- src/lib/converters.test.ts
- src/lib/converters.ts
- src/pages/_borrow/BorrowModal/BorrowStep.tsx
- src/pages/_lend/DepositModal.tsx
* feat: Update CryptoAmountSelector to support 7 decimal accuracy. Use this accuracy everywhere.
* Added a new dependency react-number-format
* feat: Update withdraw & repay to use new loading, error & success dialogs.
* feat: Add 3 XLM limit to emptying the user's wallet
* chore: tests for converters.ts
* Added vitest, set it up in the node.js Workflow
> feat: Support 7 decimal accuracy in the frontend

- contracts/loan_manager/src/contract.rs
- src/contexts/loan-context.tsx
- Changed Option to Result type for get_loan
- Quick fix to loan context fetching the loan
> Fix: loan not visible

- contracts/loan_manager/src/contract.rs
- Added function for admin to withdraw revenue
- TODO: unit testing
> feat: add admin_withdraw_revenue function

- Cargo.lock
- liquidation-bot/Cargo.toml
- liquidation-bot/src/bin/liquidation_bot.rs
Get the initial ledger and go back in history. Refactor how the environment is loaded so no need to create the same struct multiple times.
How will that initial ledger work with the local env?
2. Does your pull request change contract endpoint?
3. Does your pull request demand a new deployment of contracts
> chore: Liquidation bot initial ledger & refactoring

- scripts/util.ts
I wrote buggy code. Fixed.
2. Does your pull request change contract endpoint?
3. Does your pull request demand a new deployment of contracts
> fix: CI not having .stellar directory in place breaks things.

- src/components/AssetsModal/WithdrawView.tsx
Whoops
2. Does your pull request change contract endpoint?
3. Does your pull request demand a new deployment of contracts
> fix: withdraw view dollar value off by 10 million
